language: node_js

node_js:
  - "node"
  - "lts/*"

cache:
  directories:
    - "node_modules"
    - "public"
git:
  depth: 3

branches:
  only:
  - dev
  - master
  - /^greenkeeper/.*$/

install: npm install

before_script:
  - npm install -g mocha gulp gulp-minify gulp-clean-css del
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

script:
  - npm install

after_success:
  - chmod +x success.sh
  - ./success.sh
after_failure:
  - chmod +x fail.sh
  - ./fail.sh
